### ISSUE TITLE
SDsetup Website down.

### ISSUE THREAD

**Issue by KoggeHD** [noahc3/SDSetup#63] opened 2019-03-04 19:21 UTC
with me the website is down
<img width="1164" alt="vivaldi_2019-03-04_20-21-34" src="https://user-images.githubusercontent.com/15078048/53757124-2578f000-3ebb-11e9-83e5-60c14e25c5fd.png">

**Comment by haincha** [comment] 2019-03-04 22:06
Down for me as well.

**Comment by noahc3** [comment] 2019-03-05 02:29
Hosting provider is migrating their backbone from OSPF to IS-IS to fix some issues. They are doing the US today so the site will be down while that happens. Should be back up some time tomorrow.

**Comment by noahc3** [comment] 2019-03-05 13:28
Looks like it's back.

**Comment by WerWolv** [comment] 2019-03-05 13:30
Nope, definitely not back @noahc3 
Maybe in america only

**Comment by shchmue** [comment] 2019-03-05 13:32
sdsetup resolves and draws the background but then infinite spinny resulting in the same thing as OP, America here.

**Comment by noahc3** [comment] 2019-03-05 13:37
I guess routing might not be back up completely yet, so it might or might not be back up.  :sweat:

**Comment by ThatNerdyPikachu** [comment] 2019-03-05 15:02
this is off topic, but what host do you use?

**Comment by haincha** [comment] 2019-03-05 15:03
Back up for me.

**Comment by Simber1** [comment] 2019-03-05 15:24
Still dead in the UK

**Comment by noahc3** [comment] 2019-03-05 18:03
> this is off topic, but what host do you use?

Aulerion

**Comment by markusdanek** [comment] 2019-03-05 18:30
Is there somewhere else the guide hosted?

**Comment by noahc3** [comment] 2019-03-05 18:53
> Is there somewhere else the guide hosted?
> Maybe the guide can be added as a GitHub Wiki?

A mirror is at backup.guide.sdsetup.com, however some CSS is a little off and you can't switch themes.

**Comment by connectconnectgithub** [comment] 2019-03-05 20:37
The guide is working fine in the backup, but the biskeygen tool is not working

**Comment by noahc3** [comment] 2019-03-05 21:47
> The guide is working fine in the backup, but the biskeygen tool is not working

Nope that needs the backend to be up. You can just use biskeydump to get your bis keys.

**Comment by LilaQ** [comment] 2019-03-06 16:12
Still down for me. And I just wanted to install Atmo :(

**Comment by LilaQ** [comment] 2019-03-06 20:36
It's back up, fyi

**Comment by jme2712** [comment] 2019-03-07 00:49
Down for me on the east coast

**Comment by dexter85** [comment] 2019-03-07 10:49
Still down in Italy

**Comment by alexrdg** [comment] 2019-03-07 13:50
down for me (france)

**Comment by Kulitorum** [comment] 2019-03-07 23:24
Down Europe

**Comment by LilaQ** [comment] 2019-03-07 23:54
Still working in germany

**Comment by jme2712** [comment] 2019-03-07 23:56
Works when I tether my phone to my laptop, but when using my home WiFi on my phone and computer it does not work. What would cause this?

**Comment by LilaQ** [comment] 2019-03-07 23:58
Try using Googles DNS servers (8.8.8.8 or 8.8.8.4) in your Router / PC

**Comment by noahc3** [comment] 2019-03-08 03:11
This will definitely have nothing to do with DNS servers.

Your cellular ISP might be able to establish a full route to the server while your home ISP might not. This will happen while routing returns to normal.

Going to lock this, I'll unlock and post an update when something changes.

**Comment by noahc3** [comment] 2019-03-09 17:37
@shchmue @jme2712 @Kulitorum @alexrdg @dexter85 Can you guys check if SDSetup is back up for you?

**Comment by jme2712** [comment] 2019-03-09 18:33
Fixed on my end. Thanks.

**Comment by Simber1** [comment] 2019-03-09 19:27
all good in the uk




Get Outlook for Android







On Sat, Mar 9, 2019 at 6:33 PM +0000, "jme2712" <notifications@github.com> wrote:










Fixed on my end. Thanks.

**Comment by shchmue** [comment] 2019-03-09 19:53
working

**Comment by noahc3** [comment] 2019-03-11 13:21
Looks like the site is back.

Kosmos will be updated later today.

**Comment by nangwan** [comment] 2019-03-12 15:26
Down for me

**Comment by Krickler** [comment] 2019-03-12 16:18
Down for me as well in Germany

**Comment by jme2712** [comment] 2019-03-12 16:25
Down again for me eastern in eastern us as well

**Comment by Essasetic** [comment] 2019-03-12 19:04
The website is up again. Tested in the UK!

**Comment by jme2712** [comment] 2019-03-12 19:16
Confirmed back up for me.

**Comment by noahc3** [comment] 2019-03-13 06:42
It's down again 😭 

#73 will get done real soon

**Comment by tumGER** [comment] 2019-03-13 06:54
🦀SDSetup is gone🦀

**Comment by noahc3** [comment] 2019-03-13 15:04
🦀 SDSetup is back 🦀

**Closed by noahc3** 2019-03-13 15:04 UTC
