### ISSUE TITLE
Download crashes while packing zip file.

### ISSUE THREAD

**Issue by eALduderino** [noahc3/SDSetup#21] opened 2018-10-07 01:27 UTC
i selected the whole package after packing about 250 files it stops packing.

**Comment by noahc3** [comment] 2018-10-07 01:28
What OS and device?

**Comment by eALduderino** [comment] 2018-10-07 01:28
win 10 x64 chrome browser

**Comment by noahc3** [comment] 2018-10-07 01:29
How much RAM does your PC have?

**Comment by eALduderino** [comment] 2018-10-07 01:29
32GB

**Comment by eALduderino** [comment] 2018-10-07 01:29
already deactivated firewall and AV

**Comment by noahc3** [comment] 2018-10-07 01:30
Does anything show up in the console (f12)

**Comment by eALduderino** [comment] 2018-10-07 01:30
no it just goes from loading screen to selection website agin at 247 files

**Comment by eALduderino** [comment] 2018-10-07 01:31
same with Firefox

**Comment by eALduderino** [comment] 2018-10-07 01:32
guess there's an issue with file 247!?

**Comment by noahc3** [comment] 2018-10-07 01:32
Which packages are you selecting? (screenshots if you dont wanna type them out)

**Comment by eALduderino** [comment] 2018-10-07 01:37
i selected all, when deselcting the PC Tools it's working. i deselected one by one, didn't work. Deselected all, worked! Maybe it is a File size problem, not just a specific one.

**Comment by eALduderino** [comment] 2018-10-07 01:38
ah wait.
wen selecting just the pc tools (52) files it crashes also

**Comment by eALduderino** [comment] 2018-10-07 01:40
its nspbuild and Switch Backup Manager causing trouble

**Comment by noahc3** [comment] 2018-10-07 01:42
Ill try to fix this but I can't currently reproduce the bug. I'll test on some other machines/vms and see if I can get it to happen.

Can you tell me your Chrome version? (chrome://settings/help)

**Comment by eALduderino** [comment] 2018-10-07 01:50
Okay, no worries.  For me it's both of them. Can't download either, wether both or each by itself. It just starts packing the files and then stops. website switches from gray with loading circle to normal status., no errors. Got same behavior  with Chrome Firefox and Edge (just to be sure)... Thanks though for the quick reply and thanks a lot for the efford and providing good stuff. it's appreciated!

**Comment by joturako** [comment] 2018-10-08 04:01
@eALduderino Can you try again and this time open the Developer Tools' Console and get the whole scripts output here? I just tried to download both and it got thru, a zip is downloaded for me.

For example this is when I download SBM
> Downloading https://cdn.rawgit.com/noahc3/SDSetupFiles/master/switchbackupmanager/v1.1.7/pc/SwitchBackupManager/Changelog.txt
methods.js:86 Downloaded https://cdn.rawgit.com/noahc3/SDSetupFiles/master/switchbackupmanager/v1.1.7/pc/SwitchBackupManager/Changelog.txt

**Comment by noahc3** [comment] 2018-11-02 07:53
I'm going to close this because the bug seems very rare and potentially not an issue I can fix myself.

**Closed by noahc3** 2018-11-02 07:53 UTC
Labels: 3. bug
