### ISSUE TITLE
Duplicated files in single archive

### ISSUE THREAD

**Issue by feraligatr** [noahc3/SDSetup#99] opened 2019-06-03 16:56 UTC
I chose EVERYTHING except Retroarch. After downloading, the resulting zip file contains some duplicated files, some of which are even of different sizes.

BTW. RetroArch 1.7.7 is out.

**Comment by feraligatr** [comment] 2019-06-10 10:24
BTW, the version number of "ReiNX Toolkit" (not "ReiNX" button) is still v2.1

**Comment by noahc3** [comment] 2019-06-10 12:53
The duplicated files are due to ReiNX and Atmosphere packing different sept payloads. The problem is that fusee and reinx do not replace the payload like hekate does at this time. Best I can do is prioritize the reinx Sept since I assume most people downloading reinx plan to use reinx anyways. 

This wont happen until I get free time in early July as the server does not currently support priority.

**Comment by feraligatr** [comment] 2019-06-13 17:07
> The duplicated files are due to ReiNX and Atmosphere packing different sept payloads. The problem is that fusee and reinx do not replace the payload like hekate does at this time. Best I can do is prioritize the reinx Sept since I assume most people downloading reinx plan to use reinx anyways.
> 
> This wont happen until I get free time in early July as the server does not currently support priority.

Personally I don't think that's a good solution since ReiNX files may not be 100% compatible with Atmosphere. I prefer that they're conflict with each other so user can only choose one, not both.

**Comment by noahc3** [comment] 2019-06-13 20:00
If you use hekate to boot Atmosphere then they will not conflict (hekate temporarily moves the files and places its own there, then moves the old files back afterwards). Trying to use fuses and reinx is the problem.

**Comment by noahc3** [comment] 2019-06-20 04:49
OK so apparently at some point I put emuiibo in the ldn_mitm folder causing a duplicate... oops.

That's fixed now, still need to work on the ReiNX/Atmosphere overlap.

**Comment by noahc3** [comment] 2019-07-03 05:47
This is now fixed. ReiNX has priority over Atmosphere sept files, but note that if you ever boot Atmosphere once through hekate, ReiNX will no longer boot (since it doesn't replace the sept payload like hekate does).

**Closed by noahc3** 2019-07-03 05:47 UTC
Labels: 0. area backend, 3. bug, 8. done internally
