### ISSUE TITLE
I can not derive the keys BIS

### ISSUE THREAD

**Issue by games12366** [noahc3/SDSetup#112] opened 2019-07-28 23:28 UTC
Hello i click on drifting the keys bis and nothing happens the same with another person a technical problem?

**Comment by friedkeenan** [comment] 2019-07-28 23:29
Duplicate of #108

**Comment by games12366** [comment] 2019-07-28 23:39
Yes, but how do I recover

**Comment by noahc3** [comment] 2019-08-03 20:36
Biskeygen on SDSetup has been fixed and the guide has been corrected.

**Closed by noahc3** 2019-08-03 20:36 UTC
